-- Remove table if it exists
drop table if exists bookmarks;

-- Create table
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  bookmark_url TEXT NOT NULL,
  bookmark_description TEXT,
  rating INTEGER DEFAULT 1
);

-- Insert some test data
-- Using a multi-row insert statement here
insert into bookmarks
  (title, bookmark_url, bookmark_description, rating)
values
  ('Google', 'www.google.com', 'find all the things', 5),
  ('MDN web docs', 'www.developer.mozilla.org', 'the most reliable source', 5),
  ('Ticketmaster', 'www.ticketmaster.com', 'get tickets here', 5),
  ('Undisclosed', 'www.undisclosed-podcast.com', 'the best podcast and the best lawyers', 5),
  ('LinkedIn', 'www.linkedin.com', 'get connected', 5),
  ('GitHub', 'www.github.com', 'keep track of my stuff', 5),
  ('Thinkful', 'www.thinkful.com', 'learn to code', 5),
  ('Slack', 'www.slack.com', 'best way to communicate with colleagues', 5),
  ('Instagram', 'www.instagram.com', 'most tolerable social media and that is a stretch', 2),
  ('Pinterest', 'www.pinterest.com', 'workouts and recipes', 3)
